@api_web_learning_1_HostAddress = https://localhost:7281

GET {{api_web_learning_1_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{api_web_learning_1_HostAddress}}/api/todoitems
Content-Type: application/json
  
{
  "name": "walk dog",
  "isComplete": true
}

###
